spring:
  datasource:
    url: jdbc:mysql://db:3306/gestionappdb # 'db' is the Docker service name for MySQL
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 9090


